<script setup lang="ts">
import { reactive, ref, onMounted } from 'vue'
import { ElMessage } from 'element-plus'
import { useRoute, useRouter } from 'vue-router'
import { createActivity, getAdminActivity, updateActivity } from '@/api/admin'
const route = useRoute(); const router = useRouter(); const editing = Boolean(route.params.id); const loading = ref(false); const saving = ref(false)
const form = reactive({ title:'', coverUrl:'', description:'', activityType:'训练课', startTime:'', endTime:'', location:'', capacity:30, applyDeadline:'' })
onMounted(async () => { if (!editing) return; loading.value = true; try { Object.assign(form, (await getAdminActivity(String(route.params.id))).data) } finally { loading.value = false } })
function validate() { if (!form.title.trim() || !form.activityType.trim() || !form.location.trim()) { ElMessage.error('请填写标题、类型和地点'); return false }; if (!form.startTime || !form.endTime || !form.applyDeadline) { ElMessage.error('请填写完整时间'); return false }; if (form.startTime >= form.endTime) { ElMessage.error('开始时间必须早于结束时间'); return false }; if (form.applyDeadline >= form.startTime) { ElMessage.error('报名截止时间必须早于开始时间'); return false }; if (!Number.isInteger(form.capacity) || form.capacity <= 0) { ElMessage.error('人数上限必须为正整数'); return false }; return true }
async function save() { if (!validate()) return; saving.value = true; try { if (editing) await updateActivity(String(route.params.id), form); else await createActivity(form); ElMessage.success(editing ? '活动已保存' : '活动已创建'); await router.push('/admin/activities') } finally { saving.value = false } }
</script>
<template><section class="editor" v-loading="loading"><div class="editor-title"><div><h1>{{ editing ? '编辑活动' : '新增活动' }}</h1><p>发布前请确认时间、地点和报名截止时间。</p></div><el-button @click="router.push('/admin/activities')">返回列表</el-button></div><el-form :model="form" label-position="top" class="form"><el-form-item label="活动标题" required><el-input v-model="form.title" maxlength="100" /></el-form-item><el-form-item label="活动类型" required><el-select v-model="form.activityType" style="width:100%"><el-option label="训练课" value="训练课" /><el-option label="社团活动" value="社团活动" /><el-option label="成果展示" value="成果展示" /><el-option label="比赛" value="比赛" /></el-select></el-form-item><el-form-item label="活动描述"><el-input v-model="form.description" type="textarea" :rows="4" maxlength="10000" show-word-limit /></el-form-item><div class="two-col"><el-form-item label="开始时间" required><el-date-picker v-model="form.startTime" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" style="width:100%" /></el-form-item><el-form-item label="结束时间" required><el-date-picker v-model="form.endTime" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" style="width:100%" /></el-form-item></div><div class="two-col"><el-form-item label="报名截止时间" required><el-date-picker v-model="form.applyDeadline" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" style="width:100%" /></el-form-item><el-form-item label="人数上限" required><el-input-number v-model="form.capacity" :min="1" :precision="0" style="width:100%" /></el-form-item></div><el-form-item label="活动地点" required><el-input v-model="form.location" /></el-form-item><div><el-button type="primary" :loading="saving" @click="save">保存</el-button><el-button @click="router.push('/admin/activities')">取消</el-button></div></el-form></section></template>
<style scoped>.editor { max-width: 860px; margin: auto; padding: 0; }.editor-title { display:flex; justify-content:space-between; align-items:start; margin-bottom:22px; }.editor-title h1 { margin:0; color:var(--df-primary-950); }.editor-title p { color:#77717e; }.form { background:#fff; padding:28px; }.two-col { display:grid; grid-template-columns:1fr 1fr; gap:20px; }@media (max-width:600px) { .two-col { grid-template-columns:1fr; gap:0; } }</style>
