<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'; import { ElMessage, ElMessageBox } from 'element-plus'; import { getAdminUsers, resetAdminUserPassword, updateAdminUserRole, updateAdminUserStatus, type AdminUser } from '@/api/admin'; import AdminSearchPanel from '@/components/AdminSearchPanel.vue'; import { useRoute } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
const route=useRoute();const auth=useAuthStore();const records=ref<AdminUser[]>([]);const loading=ref(true);const total=ref(0);const page=ref(1);const roles:Record<string,string>={USER:'普通用户',ADMIN:'管理员',SUPER_ADMIN:'超级管理员'}
async function load(next=page.value){loading.value=true;page.value=next;try{const {data}=await getAdminUsers({page:page.value,pageSize:10,keyword:route.query.keyword,status:route.query.status});records.value=data.records;total.value=data.total}finally{loading.value=false}}
async function toggleStatus(row:AdminUser){await ElMessageBox.confirm(`确定${row.status?'禁用':'启用'}账号「${row.username}」吗？`,'账号状态');await updateAdminUserStatus(row.id,row.status?0:1);ElMessage.success('账号状态已更新');await load()}
async function changeRole(row:AdminUser){const answer=await ElMessageBox.prompt('请输入 USER、ADMIN 或 SUPER_ADMIN','分配角色',{inputValue:row.role,inputPattern:/^(USER|ADMIN|SUPER_ADMIN)$/,inputErrorMessage:'角色格式不正确'}).catch(()=>null);if(!answer)return;await updateAdminUserRole(row.id,answer.value);ElMessage.success('角色已更新');await load()}
async function resetPassword(row:AdminUser){const answer=await ElMessageBox.prompt('请输入新的登录密码（至少 6 位）','重置密码',{inputType:'password',inputPattern:/^.{6,64}$/,inputErrorMessage:'密码长度需为 6-64 位'}).catch(()=>null);if(!answer)return;await resetAdminUserPassword(row.id,answer.value);ElMessage.success('密码已重置')}
onMounted(()=>load());watch(()=>route.fullPath,()=>load())
</script>
<template><section class="content"><div class="title"><div><h1>用户管理</h1><p>管理账号状态、角色和登录凭证。</p></div></div><AdminSearchPanel/><el-table v-loading="loading" :data="records" stripe><el-table-column prop="username" label="账号" min-width="150"/><el-table-column prop="nickname" label="昵称"/><el-table-column label="角色"><template #default="scope">{{roles[scope.row.role]||scope.row.role}}</template></el-table-column><el-table-column label="状态"><template #default="scope"><el-tag :type="scope.row.status?'success':'info'">{{scope.row.status?'正常':'已禁用'}}</el-tag></template></el-table-column><el-table-column prop="lastLoginTime" label="最近登录" min-width="170"/><el-table-column label="操作" width="280"><template #default="scope"><el-button v-if="auth.isSuperAdmin" link @click="changeRole(scope.row)">角色</el-button><el-button link @click="resetPassword(scope.row)">重置密码</el-button><el-button link :type="scope.row.status?'danger':'success'" @click="toggleStatus(scope.row)">{{scope.row.status?'禁用':'启用'}}</el-button></template></el-table-column></el-table><el-pagination v-if="total>10" v-model:current-page="page" layout="prev, pager, next" :page-size="10" :total="total" @current-change="load"/></section></template>
<style scoped>.content{padding:0}.title{display:flex;justify-content:space-between;align-items:start;margin-bottom:20px}.title h1{margin:0;color:var(--df-primary-950)}.title p{margin:8px 0 0;color:#77717e}.el-pagination{justify-content:center;margin-top:22px}</style>
