<script setup lang="ts">
import { nextTick, onBeforeUnmount, onMounted, ref } from 'vue'
import * as echarts from 'echarts'
import { getActivityStatistics, getContentStatistics, getStatisticsOverview, getStatisticsRanking, getUserTrend, type StatisticsOverview } from '@/api/statistics'
const overview = ref<StatisticsOverview>(); const loading = ref(true); const startDate = ref(''); const endDate = ref(''); const activity = ref<Record<string, number>>({}); const ranking = ref<{ works: any[]; users: any[] }>({ works: [], users: [] })
const userChart = ref<HTMLElement>(); const contentChart = ref<HTMLElement>(); let userInstance: echarts.ECharts | undefined; let contentInstance: echarts.ECharts | undefined
const end = new Date(); endDate.value = end.toISOString().slice(0, 10); end.setDate(end.getDate() - 29); startDate.value = end.toISOString().slice(0, 10)
const cards = [['totalUsers', '总用户', '人'], ['totalMembers', '活跃成员', '人'], ['totalActivities', '活动总数', '场'], ['totalCourses', '课程总数', '门'], ['totalWorks', '公开作品', '件'], ['totalApplications', '活动报名', '次']] as const
async function load() { loading.value = true; try { const [o, trend, a, c, r] = await Promise.all([getStatisticsOverview(), getUserTrend({ startDate: startDate.value, endDate: endDate.value }), getActivityStatistics({ startDate: startDate.value, endDate: endDate.value }), getContentStatistics(), getStatisticsRanking()]); overview.value = o.data; activity.value = a.data; ranking.value = r.data; await nextTick(); renderTrend(trend.data); renderContent(c.data) } finally { loading.value = false } }
function renderTrend(data: { date: string; value: number }[]) { if (!userChart.value) return; userInstance?.dispose(); userInstance = echarts.init(userChart.value); userInstance.setOption({ tooltip: { trigger: 'axis' }, grid: { left: 34, right: 18, top: 18, bottom: 26 }, xAxis: { type: 'category', data: data.map(item => item.date.slice(5)) }, yAxis: { type: 'value', minInterval: 1 }, series: [{ type: 'bar', barMaxWidth: 28, data: data.map(item => item.value), itemStyle: { color: '#8c3fa3', borderRadius: [4, 4, 0, 0] } }] }) }
function renderContent(data: Record<string, number>) { if (!contentChart.value) return; contentInstance?.dispose(); contentInstance = echarts.init(contentChart.value); contentInstance.setOption({ tooltip: { trigger: 'item' }, legend: { bottom: 0 }, series: [{ type: 'pie', radius: ['42%', '68%'], data: [{ name: '作品', value: data.works }, { name: '讨论', value: data.posts }, { name: '评论', value: data.comments }, { name: '点赞', value: data.likes }, { name: '收藏', value: data.collections }] }] }) }
function resize() { userInstance?.resize(); contentInstance?.resize() }
onMounted(() => { load(); window.addEventListener('resize', resize) }); onBeforeUnmount(() => { window.removeEventListener('resize', resize); userInstance?.dispose(); contentInstance?.dispose() })
</script>
<template><section class="dashboard" v-loading="loading"><div class="dashboard-heading"><div><p class="eyebrow">DASHBOARD</p><h1>数据工作台</h1><p>掌握社团运营状态与内容活跃情况。</p></div><div class="filters"><el-date-picker v-model="startDate" type="date" value-format="YYYY-MM-DD" placeholder="开始日期"/><span>至</span><el-date-picker v-model="endDate" type="date" value-format="YYYY-MM-DD" placeholder="结束日期"/><el-button type="primary" @click="load">刷新数据</el-button></div></div><div class="metric-grid"><article v-for="card in cards" :key="card[0]"><span>{{card[1]}}</span><strong>{{overview?.[card[0]] ?? '-'}}</strong><small>{{card[2]}}</small></article></div><div class="chart-grid"><section class="panel"><div class="panel-heading"><h2>用户增长</h2><span>按日统计</span></div><div ref="userChart" class="chart"/></section><section class="panel"><div class="panel-heading"><h2>内容分布</h2><span>当前累计</span></div><div ref="contentChart" class="chart"/></section></div><div class="lower-grid"><section class="panel"><div class="panel-heading"><h2>活动概览</h2><span>当前日期范围</span></div><div class="activity-stats"><div><strong>{{activity.published ?? 0}}</strong><span>发布活动</span></div><div><strong>{{activity.applications ?? 0}}</strong><span>新增报名</span></div><div><strong>{{activity.finished ?? 0}}</strong><span>已完成</span></div></div></section><section class="panel"><div class="panel-heading"><h2>热门作品</h2><span>按获赞排序</span></div><el-empty v-if="!ranking.works.length" description="暂无排行数据"/><div v-for="(item,index) in ranking.works" v-else :key="item.id" class="ranking-row"><b>{{index+1}}</b><span>{{item.name}}</span><small>{{item.value}} 赞</small></div></section></div></section></template>
<style scoped>.dashboard{min-height:calc(100vh - 56px)}.dashboard-heading{display:flex;align-items:flex-end;justify-content:space-between;gap:20px;margin-bottom:24px}.eyebrow{margin:0 0 8px;color:#8c3fa3;font-size:11px;letter-spacing:2px;font-weight:700}.dashboard h1{margin:0;color:var(--df-primary-950);font-size:30px}.dashboard-heading p:last-child{margin:8px 0 0;color:#77717e}.filters{display:flex;align-items:center;gap:8px}.filters .el-date-editor{width:150px}.metric-grid{display:grid;grid-template-columns:repeat(6,1fr);gap:12px}.metric-grid article,.panel{border:1px solid #e8e2ed;border-radius:8px;background:#fff}.metric-grid article{padding:18px}.metric-grid span,.metric-grid small{display:block;color:#77717e;font-size:12px}.metric-grid strong{display:inline-block;margin:12px 3px 2px 0;color:var(--df-primary-950);font-size:28px}.chart-grid,.lower-grid{display:grid;gap:16px;margin-top:16px}.chart-grid{grid-template-columns:1.5fr 1fr}.lower-grid{grid-template-columns:1fr 1fr}.panel{padding:18px}.panel-heading{display:flex;align-items:center;justify-content:space-between}.panel-heading h2{margin:0;color:#302436;font-size:16px}.panel-heading span{color:#9b91a1;font-size:12px}.chart{height:250px}.activity-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:28px}.activity-stats div{padding:18px;border-radius:6px;background:#f8f5fa;text-align:center}.activity-stats strong{display:block;color:#8c3fa3;font-size:28px}.activity-stats span{color:#77717e;font-size:12px}.ranking-row{display:flex;align-items:center;gap:12px;padding:13px 0;border-bottom:1px solid #f0ecf2;color:#564b5b}.ranking-row b{width:20px;color:#8c3fa3}.ranking-row span{flex:1}.ranking-row small{color:#8b7d91}@media(max-width:1000px){.metric-grid{grid-template-columns:repeat(3,1fr)}.dashboard-heading{align-items:flex-start;flex-direction:column}.chart-grid,.lower-grid{grid-template-columns:1fr}}@media(max-width:600px){.metric-grid{grid-template-columns:repeat(2,1fr)}.filters{width:100%;flex-wrap:wrap}.filters .el-date-editor{width:calc(50% - 18px)}.filters .el-button{width:100%}}
</style>
