<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { getNotices, getPosts, type ForumPost, type Notice } from '@/api/community'
import { getWorks, type Work } from '@/api/works'
const router = useRouter(); const tab = ref('works'); const posts = ref<ForumPost[]>([]); const works = ref<Work[]>([]); const notices = ref<Notice[]>([]); const loading = ref(false)
async function load() { loading.value = true; try { const [noticeResult, postResult, workResult] = await Promise.all([getNotices(), getPosts({ page: 1, pageSize: 12 }), getWorks({ page: 1, pageSize: 12 })]); notices.value = noticeResult.data; posts.value = postResult.data.records; works.value = workResult.data.records } finally { loading.value = false } }
function format(value?: string) { return value?.replace('T', ' ').slice(0, 16) || '' }
onMounted(load)
</script>
<template><main class="community-page"><section class="community-heading"><div><p class="eyebrow">FLOWARTIST COMMUNITY</p><h1>作品与讨论，在同一个社区</h1><p>分享你的舞台，也交流每一次练习里的想法。</p></div><el-button type="primary" @click="router.push(tab === 'works' ? '/works/create' : '/community/posts/create')">{{ tab === 'works' ? '发布作品' : '发布讨论' }}</el-button></section><section v-if="notices.length" class="notice-strip"><span class="notice-mark">公告</span><div class="notice-list"><button v-for="notice in notices.slice(0, 3)" :key="notice.id" type="button" @click="router.push(`/notices/${notice.id}`)">{{ notice.topFlag ? '置顶 · ' : '' }}{{ notice.title }}</button></div></section><section class="community-toolbar"><el-segmented v-model="tab" :options="[{ label: '作品', value: 'works' }, { label: '讨论', value: 'posts' }]" /></section><section v-loading="loading" class="community-content"><div v-if="tab === 'works'" class="work-grid"><article v-for="work in works" :key="work.id" class="work-card" @click="router.push(`/works/${work.id}`)"><div class="work-media"><img v-if="work.mediaType === 'IMAGE'" :src="work.mediaUrl" :alt="work.title" /><video v-else :src="work.mediaUrl" muted preload="metadata" /></div><div class="work-copy"><span>{{ work.danceType }}</span><h2>{{ work.title }}</h2><p>{{ work.authorName }} · {{ work.likeCount }} 赞 · {{ work.commentCount }} 评论</p></div></article><el-empty v-if="!works.length" description="暂无公开作品" /></div><div v-else class="post-grid"><article v-for="post in posts" :key="post.id" class="post-card" @click="router.push(`/community/posts/${post.id}`)"><span>{{ post.category }}</span><h2>{{ post.title }}</h2><p>{{ post.content }}</p><footer>{{ post.authorName }} · {{ format(post.createdAt) }} · {{ post.viewCount }} 浏览</footer></article><el-empty v-if="!posts.length" description="暂无讨论" /></div></section></main></template>
<style scoped>.community-page{min-height:100vh;padding:58px 24px 72px;color:#fff}.community-heading,.community-toolbar,.community-content,.notice-strip{max-width:1120px;margin-inline:auto}.community-heading{display:flex;align-items:end;justify-content:space-between;gap:24px}.eyebrow{margin:0 0 10px;color:#f0a8fb;font-size:12px;letter-spacing:2px;font-weight:700}.community-heading h1{margin:0 0 12px;font-size:42px}.community-heading p{margin:0;color:rgba(255,255,255,.7)}.notice-strip{display:flex;gap:16px;margin-top:34px;padding:14px 18px;border:1px solid rgba(244,205,250,.24);border-radius:8px;background:rgba(54,12,70,.68)}.notice-mark{color:#f0a8fb;font-size:13px;font-weight:700}.notice-list{display:flex;gap:18px;overflow:auto}.notice-list button{padding:0;border:0;background:transparent;color:rgba(255,255,255,.84);white-space:nowrap;cursor:pointer}.community-toolbar{margin-top:28px}.community-content{min-height:320px;margin-top:22px}.work-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:18px}.work-card,.post-card{overflow:hidden;border:1px solid rgba(244,205,250,.24);border-radius:10px;background:rgba(54,12,70,.8);box-shadow:0 14px 32px rgba(25,3,40,.18);cursor:pointer}.work-media{height:184px;background:#310d45}.work-media img,.work-media video{width:100%;height:100%;object-fit:cover}.work-copy{padding:14px}.work-copy span,.post-card>span{color:#f0a8fb;font-size:12px}.work-copy h2,.post-card h2{margin:8px 0;color:#fff;font-size:18px}.work-copy p,.post-card footer{margin:0;color:rgba(255,255,255,.64);font-size:12px}.post-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.post-card{padding:20px}.post-card p{display:-webkit-box;margin:12px 0 20px;overflow:hidden;color:rgba(255,255,255,.76);line-height:1.7;-webkit-line-clamp:3;-webkit-box-orient:vertical}@media(max-width:800px){.work-grid{grid-template-columns:repeat(2,1fr)}.post-grid{grid-template-columns:1fr}.community-heading{align-items:start;flex-direction:column}}@media(max-width:520px){.community-page{padding-inline:16px}.work-grid{grid-template-columns:1fr}.community-heading h1{font-size:32px}}</style>
