<script setup lang="ts">
import { onMounted, ref } from 'vue'
import UserTopbar from '@/components/UserTopbar.vue'
import { getCourses, type Course } from '@/api/courses'

const records = ref<Course[]>([]); const total = ref(0); const page = ref(1); const loading = ref(false); const keyword = ref(''); const danceType = ref(''); const difficulty = ref('')
async function load() { loading.value = true; try { const result = await getCourses({ page: page.value, pageSize: 9, keyword: keyword.value || undefined, danceType: danceType.value || undefined, difficulty: difficulty.value || undefined }); records.value = result.data.records; total.value = result.data.total } finally { loading.value = false } }
function search() { page.value = 1; load() }
onMounted(load)
</script>

<template>
  <main class="courses-page"><UserTopbar />
    <section class="hero"><p class="eyebrow">DANCE ACADEMY</p><h1>把每一次练习，变成身体的记忆。</h1><p>按舞种和难度找到适合你的课程，从基础律动开始持续进步。</p></section>
    <section class="toolbar"><el-input v-model="keyword" clearable placeholder="搜索课程或老师" @keyup.enter="search" /><el-select v-model="danceType" clearable placeholder="全部舞种"><el-option label="Hip-hop" value="Hip-hop" /><el-option label="Jazz Funk" value="Jazz Funk" /><el-option label="Performance" value="Performance" /></el-select><el-select v-model="difficulty" clearable placeholder="全部难度"><el-option label="入门" value="BEGINNER" /><el-option label="进阶" value="INTERMEDIATE" /><el-option label="高级" value="ADVANCED" /></el-select><el-button type="primary" @click="search">搜索</el-button></section>
    <section v-loading="loading" class="course-grid"><el-empty v-if="!loading && !records.length" description="暂无已发布课程" /><article v-for="course in records" :key="course.id" class="course-card" @click="router.push(`/courses/${course.id}`)"><div class="cover"><span>{{ course.danceType }}</span><strong>{{ course.difficulty === 'BEGINNER' ? '入门' : course.difficulty === 'INTERMEDIATE' ? '进阶' : '高级' }}</strong></div><div class="card-body"><p class="teacher">{{ course.teacherName }} · {{ course.lessonCount }} 个课时</p><h2>{{ course.title }}</h2><p>{{ course.description || '跟随老师完成一套系统的舞蹈训练。' }}</p><el-button link type="primary">开始学习 →</el-button></div></article></section><el-pagination v-if="total" v-model:current-page="page" layout="prev, pager, next" :page-size="9" :total="total" @current-change="load" />
  </main>
</template>

<style scoped>
.courses-page { min-height: 100vh; background: linear-gradient(145deg, #fbf7ff 0%, #f6effa 48%, #fff 100%); color: #302436; }.topbar { height: 68px; display: flex; align-items: center; justify-content: space-between; padding: 0 5vw; background: rgba(255,255,255,.9); border-bottom: 1px solid #eee8f1; }.topbar nav { display: flex; gap: 22px; }.hero { max-width: 1120px; margin: auto; padding: 72px 24px 44px; }.eyebrow, .teacher { color: var(--df-primary-700); letter-spacing: 2px; font-size: 11px; font-weight: 700; }.hero h1 { max-width: 650px; margin: 14px 0 12px; color: var(--df-primary-950); font-size: clamp(34px, 5vw, 56px); line-height: 1.18; }.hero > p:last-child { color: #766b7b; line-height: 1.8; }.toolbar { display: flex; gap: 12px; max-width: 1120px; margin: auto; padding: 0 24px 28px; }.toolbar .el-input { max-width: 310px; }.toolbar .el-select { width: 150px; }.course-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; max-width: 1120px; min-height: 240px; margin: auto; padding: 0 24px 34px; }.course-card { overflow: hidden; border: 1px solid #eee8f1; border-radius: 10px; background: #fff; cursor: pointer; transition: transform .2s, box-shadow .2s; }.course-card:hover { transform: translateY(-4px); box-shadow: 0 14px 32px rgba(77,34,92,.12); }.cover { height: 142px; display: flex; align-items: flex-end; justify-content: space-between; padding: 18px; color: #fff; background: linear-gradient(135deg, var(--df-primary-950), var(--df-primary-500)); }.cover strong { padding: 5px 9px; border: 1px solid rgba(255,255,255,.35); border-radius: 999px; font-size: 11px; }.card-body { padding: 18px; }.teacher { margin: 0; letter-spacing: 0; }.card-body h2 { margin: 10px 0; font-size: 20px; }.card-body p:not(.teacher) { height: 44px; margin-bottom: 12px; overflow: hidden; color: #766b7b; line-height: 1.55; }.el-pagination { justify-content: center; padding-bottom: 48px; }
@media (max-width: 760px) { .topbar { padding: 0 18px; }.topbar nav { gap: 10px; }.hero { padding-top: 48px; }.toolbar { flex-wrap: wrap; }.toolbar .el-input { max-width: none; width: 100%; }.course-grid { grid-template-columns: repeat(2, 1fr); } } @media (max-width: 520px) { .course-grid { grid-template-columns: 1fr; } }
</style>
