<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import BrandLogo from '@/components/BrandLogo.vue'
import { getCourse, type Course } from '@/api/courses'
import { useAuthStore } from '@/stores/auth'
const route = useRoute(); const router = useRouter(); const auth = useAuthStore(); const course = ref<Course | null>(null); const loading = ref(true)
onMounted(async () => { try { course.value = (await getCourse(String(route.params.id))).data } finally { loading.value = false } })
function learn(id: string | number) { if (!auth.isLoggedIn) { router.push({ name: 'login', query: { redirect: route.fullPath } }); return }; router.push(`/courses/${route.params.id}/lessons/${id}`) }
</script>
<template><main class="detail-page"><header class="topbar"><BrandLogo variant="purple" :height="34" to="/" /><el-link @click="router.push('/courses')">返回课程中心</el-link></header><section v-loading="loading" class="detail"><template v-if="course"><p class="eyebrow">{{ course.danceType }} · {{ course.teacherName }}</p><h1>{{ course.title }}</h1><p class="description">{{ course.description }}</p><div class="progress-row"><span>学习进度</span><el-progress :percentage="course.progressPercent || 0" /></div><h2>课程目录 <small>{{ course.lessons?.length || 0 }} 个课时</small></h2><div class="lesson-list"><article v-for="lesson in course.lessons" :key="lesson.id" class="lesson" @click="learn(lesson.id)"><span class="number">{{ String(lesson.sortNo).padStart(2, '0') }}</span><div><h3>{{ lesson.title }}</h3><p>{{ Math.floor(lesson.duration / 60) }} 分钟 · {{ lesson.completed ? '已完成' : lesson.progressSeconds ? '学习中' : '未开始' }}</p></div><el-button link type="primary">学习 →</el-button></article></div></template></section></main></template>
<style scoped>.detail-page { min-height: 100vh; background: #fbfbfd; }.topbar { height: 68px; display: flex; align-items: center; justify-content: space-between; padding: 0 5vw; background: #fff; border-bottom: 1px solid #eee8f1; }.detail { max-width: 850px; margin: auto; padding: 70px 24px; }.eyebrow { color: var(--df-primary-700); letter-spacing: 1.5px; font-size: 12px; }.detail h1 { margin: 14px 0; color: var(--df-primary-950); font-size: clamp(34px, 5vw, 52px); }.description { max-width: 680px; color: #766b7b; line-height: 1.9; }.progress-row { display: flex; align-items: center; gap: 18px; margin: 38px 0 48px; color: #766b7b; }.progress-row .el-progress { width: 260px; }.detail h2 { color: var(--df-primary-950); }.detail h2 small { margin-left: 8px; color: #998e9e; font-size: 12px; font-weight: 400; }.lesson-list { margin-top: 18px; border-top: 1px solid #e9e1eb; }.lesson { display: flex; align-items: center; gap: 18px; padding: 20px 4px; border-bottom: 1px solid #e9e1eb; cursor: pointer; }.lesson:hover h3 { color: var(--df-primary-600); }.number { color: var(--df-primary-400); font-size: 22px; font-weight: 700; }.lesson div { flex: 1; }.lesson h3 { margin: 0 0 6px; font-size: 16px; }.lesson p { margin: 0; color: #998e9e; font-size: 12px; }</style>
