<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import BrandLogo from '@/components/BrandLogo.vue'
import { getLesson, saveLessonProgress, type LessonLearning } from '@/api/courses'
const route = useRoute(); const router = useRouter(); const data = ref<LessonLearning | null>(null); const loading = ref(true); const saving = ref(false); const player = ref<HTMLVideoElement>(); const progress = ref(0); let timer: ReturnType<typeof setInterval> | undefined
onMounted(async () => { try { data.value = (await getLesson(String(route.params.id), String(route.params.lessonId))).data; progress.value = data.value.lesson.progressSeconds || 0; timer = setInterval(saveProgress, 15000) } finally { loading.value = false } })
onUnmounted(() => { if (timer) clearInterval(timer) })
async function saveProgress(completed = false) { if (!data.value || saving.value) return; saving.value = true; try { const seconds = player.value ? Math.floor(player.value.currentTime) : progress.value; progress.value = seconds; await saveLessonProgress(String(route.params.id), String(route.params.lessonId), { progressSeconds: seconds, completed }); } catch { /* request interceptor displays the error */ } finally { saving.value = false } }
async function complete() { await saveProgress(true); ElMessage.success('本课时已完成') }
</script>
<template><main class="learn-page"><header class="topbar"><BrandLogo variant="purple" :height="34" to="/" /><el-link @click="router.push(`/courses/${route.params.id}`)">返回课程详情</el-link></header><section v-loading="loading" class="learning"><template v-if="data"><p class="eyebrow">{{ data.course.title }}</p><h1>{{ data.lesson.title }}</h1><div class="player"><video v-if="data.lesson.videoUrl" ref="player" controls :src="data.lesson.videoUrl" @timeupdate="progress = Math.floor(($event.target as HTMLVideoElement).currentTime)" @pause="saveProgress()" /><div v-else class="player-empty"><span>VIDEO</span><p>本课时暂未配置视频，先阅读下方训练内容吧。</p></div></div><div class="lesson-content"><p>{{ data.lesson.content || '跟随课程节奏完成练习，注意动作细节和身体控制。' }}</p><div class="actions"><span>已学习 {{ Math.floor(progress / 60) }} 分钟</span><el-button type="primary" :loading="saving" @click="complete">标记为已完成</el-button></div></div></template></section></main></template>
<style scoped>.learn-page { min-height: 100vh; background: #fbfbfd; }.topbar { height: 68px; display: flex; align-items: center; justify-content: space-between; padding: 0 5vw; background: #fff; border-bottom: 1px solid #eee8f1; }.learning { max-width: 900px; margin: auto; padding: 56px 24px; }.eyebrow { color: var(--df-primary-700); font-size: 12px; letter-spacing: 1.5px; }.learning h1 { margin: 12px 0 28px; color: var(--df-primary-950); font-size: 38px; }.player { min-height: 430px; display: grid; place-items: center; overflow: hidden; border-radius: 12px; background: linear-gradient(135deg, #29143f, #7d3290); }.player video { width: 100%; max-height: 520px; }.player-empty { color: #fff; text-align: center; }.player-empty span { font-size: 64px; font-weight: 800; letter-spacing: 4px; opacity: .2; }.player-empty p { color: rgba(255,255,255,.75); }.lesson-content { padding: 28px 0; color: #665b6c; line-height: 1.9; }.actions { display: flex; align-items: center; justify-content: space-between; margin-top: 30px; padding-top: 20px; border-top: 1px solid #e9e1eb; font-size: 13px; }</style>
