<script setup lang="ts">
import { onMounted, reactive, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { getMembers, getMember, auditMember, updateMember, updateMemberStatus } from '@/api/admin'
import type { MemberProfile } from '@/api/club'
const records = ref<MemberProfile[]>([]); const loading = ref(true); const drawerVisible = ref(false); const drawerLoading = ref(false); const saving = ref(false); const selected = ref<MemberProfile | null>(null)
const route = useRoute()
const form = reactive({ danceType: '', skillLevel: '', bio: '' })
async function load() { loading.value = true; try { const all = (await getMembers()).data.records; const keyword = String(route.query.keyword || '').toLowerCase(); records.value = all.filter(item => (!keyword || `${item.nickname} ${item.username}`.toLowerCase().includes(keyword)) && (!route.query.danceType || item.danceType === route.query.danceType) && (!route.query.status || item.memberStatus === route.query.status)) } finally { loading.value = false } }
onMounted(load)
watch(() => route.fullPath, load)
async function openDetail(row: MemberProfile) { drawerVisible.value = true; drawerLoading.value = true; try { selected.value = (await getMember(row.id)).data; Object.assign(form, { danceType: selected.value.danceType, skillLevel: selected.value.skillLevel, bio: selected.value.bio || '' }) } finally { drawerLoading.value = false } }
async function save() { if (!selected.value) return; saving.value = true; try { selected.value = (await updateMember(selected.value.id, form)).data; ElMessage.success('档案已保存'); await load() } finally { saving.value = false } }
async function audit(row: MemberProfile, status: string) { const reason = await ElMessageBox.prompt('可填写审核说明', '审核申请', { inputPlaceholder: '审核说明' }).then(r => r.value).catch(() => null); if (reason === null) return; await auditMember(row.id, status, reason); ElMessage.success('审核完成'); await load() }
async function changeStatus(status: string) { if (!selected.value) return; await updateMemberStatus(selected.value.id, status); ElMessage.success('状态已更新'); await openDetail(selected.value); await load() }
const labels: Record<string, string> = { PENDING: '审核中', ACTIVE: '已加入', REJECTED: '未通过', QUIT: '已退出' }
</script>
<template><main class="admin-page"><section class="content"><div class="title"><div><h1>成员审核</h1><p>查看成员档案，处理入社申请。</p></div><el-button @click="load">刷新</el-button></div><el-table v-loading="loading" :data="records" stripe><el-table-column prop="nickname" label="昵称" /><el-table-column prop="danceType" label="舞种" /><el-table-column prop="skillLevel" label="等级" /><el-table-column label="状态"><template #default="scope"><el-tag>{{ labels[scope.row.memberStatus] }}</el-tag></template></el-table-column><el-table-column label="操作" width="230"><template #default="scope"><el-button link @click="openDetail(scope.row)">查看</el-button><el-button v-if="scope.row.memberStatus === 'PENDING'" type="success" link @click="audit(scope.row, 'ACTIVE')">通过</el-button><el-button v-if="scope.row.memberStatus === 'PENDING'" type="danger" link @click="audit(scope.row, 'REJECTED')">拒绝</el-button></template></el-table-column></el-table><el-empty v-if="!loading && !records.length" description="暂无成员记录" /></section><el-drawer v-model="drawerVisible" title="成员档案" size="420px"><div v-loading="drawerLoading" class="drawer-body" v-if="selected"><el-descriptions :column="1" border><el-descriptions-item label="昵称">{{ selected.nickname }}</el-descriptions-item><el-descriptions-item label="账号">{{ selected.username }}</el-descriptions-item><el-descriptions-item label="状态">{{ labels[selected.memberStatus] }}</el-descriptions-item></el-descriptions><el-form :model="form" label-position="top" class="edit-form"><el-form-item label="舞种"><el-input v-model="form.danceType" /></el-form-item><el-form-item label="等级"><el-input v-model="form.skillLevel" /></el-form-item><el-form-item label="简介"><el-input v-model="form.bio" type="textarea" :rows="4" /></el-form-item><el-button type="primary" :loading="saving" @click="save">保存档案</el-button><el-button v-if="selected.memberStatus === 'ACTIVE'" type="warning" @click="changeStatus('QUIT')">设为退出</el-button></el-form></div></el-drawer></main></template>
<style scoped>.admin-page { min-height: auto; background: transparent; }.content { padding: 0; }.title { display: flex; justify-content: space-between; align-items: start; margin-bottom: 20px; }.title h1 { margin: 0; color: var(--df-primary-950); }.title p { margin: 8px 0 0; color: #77717e; }.drawer-body { min-height: 240px; }.edit-form { margin-top: 24px; }</style>
