<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { getMyApplications, type ActivityApply } from '@/api/activities'

const records = ref<ActivityApply[]>([]); const loading = ref(true)
onMounted(async () => { try { records.value = (await getMyApplications()).data } finally { loading.value = false } })
const labels: Record<string, string> = { APPLIED: '已报名', CANCELLED: '已取消' }
</script>

<template><main class="applications-page"><section class="content"><div class="page-heading"><p class="eyebrow">MY APPLICATIONS</p><h1>我的报名</h1><p>查看你参与过的社团活动和报名状态。</p></div><div class="table-panel"><el-table v-loading="loading" :data="records" stripe><el-table-column prop="activityId" label="活动编号" width="120" /><el-table-column prop="applyTime" label="报名时间" /><el-table-column prop="remark" label="备注" /><el-table-column label="状态" width="110"><template #default="scope"><el-tag :type="scope.row.applyStatus === 'APPLIED' ? 'success' : 'info'">{{ labels[scope.row.applyStatus] || scope.row.applyStatus }}</el-tag></template></el-table-column></el-table><el-empty v-if="!loading && !records.length" description="还没有报名记录" /></div></section></main></template>

<style scoped>.applications-page { min-height: 100vh; background: transparent; color: rgba(255,255,255,.9); }.content { max-width: 1040px; margin: auto; padding: 64px 24px; }.page-heading { margin-bottom: 30px; }.eyebrow { margin: 0 0 10px; color: #f0a8fb; font-size: 12px; font-weight: 700; letter-spacing: 2px; }.page-heading h1 { margin: 0 0 10px; color: #fff; font-size: 42px; }.page-heading p:last-child { margin: 0; color: rgba(255,255,255,.7); }.table-panel { overflow: hidden; border: 1px solid rgba(244,205,250,.24); border-radius: 14px; background: rgba(54,12,70,.8); box-shadow: 0 16px 38px rgba(25,3,40,.24); backdrop-filter: blur(14px); }.table-panel :deep(.el-table), .table-panel :deep(.el-table__expanded-cell) { background: transparent; color: rgba(255,255,255,.9); }.table-panel :deep(.el-table th.el-table__cell) { background: rgba(255,255,255,.1); color: rgba(255,255,255,.8); }.table-panel :deep(.el-table td.el-table__cell) { background: transparent; color: rgba(255,255,255,.9); border-color: rgba(244,205,250,.18); }.table-panel :deep(.el-table--striped .el-table__body tr.el-table__row--striped td.el-table__cell) { background: rgba(255,255,255,.035); }.table-panel :deep(.el-table__body tr:hover > td.el-table__cell) { background: rgba(240,168,251,.1); }</style>
