<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import type { LearningCourse } from '@/api/courses'
import { getProfileCourses } from '@/api/profile'
const router = useRouter(); const records = ref<LearningCourse[]>([]); const loading = ref(true); const page = ref(1); const total = ref(0)
async function load(nextPage = page.value) { loading.value = true; page.value = nextPage; try { const { data } = await getProfileCourses({ page: page.value, pageSize: 10 }); records.value = data.records; total.value = data.total } finally { loading.value = false } }
onMounted(load)
</script>
<template><main class="my-page"><section class="content"><div class="page-heading"><p class="eyebrow">MY LEARNING</p><h1>我的学习</h1><p>继续你的课程训练，记录每一次进步。</p></div><div v-loading="loading" class="list"><el-empty v-if="!loading && !records.length" description="还没有开始学习课程" /><article v-for="item in records" :key="item.courseId" @click="router.push(`/courses/${item.courseId}`)"><div class="cover">{{ item.danceType }}</div><div class="info"><h2>{{ item.title }}</h2><p>{{ item.completedCount }} / {{ item.lessonCount }} 个课时已完成</p><el-progress :percentage="item.progressPercent" /></div><el-button link type="primary">继续学习 →</el-button></article></div><el-pagination v-if="total > 10" v-model:current-page="page" layout="prev, pager, next" :page-size="10" :total="total" @current-change="load" /></section></main></template>
<style scoped>.my-page { min-height: 100vh; background: transparent; color: rgba(255,255,255,.9); }.content { max-width: 1040px; margin: auto; padding: 64px 24px; }.page-heading { margin-bottom: 30px; }.eyebrow { margin: 0 0 10px; color: #f0a8fb; letter-spacing: 2px; font-size: 12px; font-weight: 700; }.page-heading h1 { margin: 0 0 10px; color: #fff; font-size: 42px; }.page-heading p:last-child { margin: 0; color: rgba(255,255,255,.7); }.list { min-height: 240px; }.list article { display: flex; align-items: center; gap: 20px; margin-bottom: 14px; padding: 18px 20px; border: 1px solid rgba(244,205,250,.24); border-radius: 14px; background: rgba(54,12,70,.8); box-shadow: 0 14px 32px rgba(25,3,40,.2); cursor: pointer; transition: transform .2s, border-color .2s, background .2s; }.list article:hover { transform: translateY(-3px); border-color: rgba(240,168,251,.55); background: rgba(76,18,91,.9); }.cover { width: 112px; height: 78px; display: grid; place-items: center; flex-shrink: 0; border-radius: 9px; background: linear-gradient(135deg, #35104b, #c52fda); color: #fff; font-size: 13px; font-weight: 700; }.info { flex: 1; }.info h2 { margin: 0 0 7px; color: #fff; font-size: 18px; }.info p { margin: 0 0 10px; color: rgba(255,255,255,.72); font-size: 13px; }.info :deep(.el-progress-bar__outer) { background: rgba(255,255,255,.14); }.info :deep(.el-progress__text) { color: rgba(255,255,255,.78); }.list :deep(.el-button.is-link) { color: #f0a8fb; }@media (max-width: 600px) { .list article { align-items: flex-start; flex-wrap: wrap; }.list article .info { min-width: calc(100% - 132px); }.list article .el-button { margin-left: 132px; } }</style>
