<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { getMyLearning, type LearningCourse } from '@/api/courses'
const router = useRouter(); const records = ref<LearningCourse[]>([]); const loading = ref(true)
onMounted(async () => { try { records.value = (await getMyLearning()).data } finally { loading.value = false } })
</script>
<template><main class="my-page"><UserTopbar /><section class="content"><p class="eyebrow">MY LEARNING</p><h1>我的学习</h1><div v-loading="loading" class="list"><el-empty v-if="!loading && !records.length" description="还没有开始学习课程" /><article v-for="item in records" :key="item.courseId" @click="router.push(`/courses/${item.courseId}`)"><div class="cover">{{ item.danceType }}</div><div class="info"><h2>{{ item.title }}</h2><p>{{ item.completedCount }} / {{ item.lessonCount }} 个课时已完成</p><el-progress :percentage="item.progressPercent" /></div><el-button link type="primary">继续学习 →</el-button></article></div></section></main></template>
<style scoped>.my-page { min-height: 100vh; background: linear-gradient(145deg, #fbf7ff 0%, #f6effa 48%, #fff 100%); }.topbar { height: 68px; display: flex; align-items: center; justify-content: space-between; padding: 0 5vw; background: #fff; border-bottom: 1px solid #eee8f1; }.content { max-width: 850px; margin: auto; padding: 64px 24px; }.eyebrow { color: var(--df-primary-700); letter-spacing: 2px; font-size: 11px; font-weight: 700; }.content h1 { margin: 12px 0 34px; color: var(--df-primary-950); font-size: 42px; }.list { min-height: 240px; }.list article { display: flex; align-items: center; gap: 20px; padding: 18px 0; border-bottom: 1px solid #e9e1eb; cursor: pointer; }.cover { width: 100px; height: 72px; display: grid; place-items: center; flex-shrink: 0; border-radius: 8px; background: linear-gradient(135deg, var(--df-primary-950), var(--df-primary-500)); color: #fff; font-size: 12px; }.info { flex: 1; }.info h2 { margin: 0 0 6px; font-size: 17px; }.info p { margin: 0 0 9px; color: #766b7b; font-size: 12px; }.info .el-progress { max-width: 300px; }</style>
