<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { getMyWorks, type Work } from '@/api/works'
const router = useRouter(); const records = ref<Work[]>([]); const loading = ref(true); const labels: Record<string,string> = { PENDING:'审核中', PUBLISHED:'已发布', REJECTED:'已驳回', OFFLINE:'已下架' }
onMounted(async () => { try { records.value = (await getMyWorks({ page:1, pageSize:100 })).data.records } finally { loading.value = false } })
</script>
<template><main class="my-works"><section class="content"><div class="heading"><div><p class="eyebrow">MY WORKS</p><h1>我的作品</h1><p>查看作品审核状态和互动数据。</p></div><el-button type="primary" @click="router.push('/works/create')">发布作品</el-button></div><div v-loading="loading" class="list"><el-empty v-if="!loading&&!records.length" description="还没有发布作品" /><article v-for="work in records" :key="work.id"><div class="thumb"><img v-if="work.mediaType==='IMAGE'" :src="work.mediaUrl" :alt="work.title" /><span v-else>VIDEO</span></div><div class="info"><h2>{{ work.title }}</h2><p>{{ work.danceType }} · {{ work.likeCount }} 赞 · {{ work.commentCount }} 评论</p><el-tag :type="work.auditStatus==='PUBLISHED'?'success':work.auditStatus==='REJECTED'?'danger':'warning'">{{ labels[work.auditStatus] }}</el-tag><p v-if="work.auditReason" class="reason">驳回原因：{{ work.auditReason }}</p></div><el-button link type="primary" @click="router.push(`/works/${work.id}`)">查看详情</el-button></article></div></section></main></template>
<style scoped>.my-works{min-height:100vh;background:transparent;color:#fff}.content{max-width:1040px;margin:auto;padding:64px 24px}.heading{display:flex;align-items:end;justify-content:space-between;margin-bottom:30px}.eyebrow{margin:0 0 10px;color:#f0a8fb;font-size:12px;font-weight:700;letter-spacing:2px}.heading h1{margin:0 0 10px;font-size:42px}.heading p:last-child{margin:0;color:rgba(255,255,255,.7)}.list{min-height:240px}.list article{display:flex;align-items:center;gap:18px;margin-bottom:14px;padding:16px 20px;border:1px solid rgba(244,205,250,.24);border-radius:14px;background:rgba(54,12,70,.8);box-shadow:0 14px 32px rgba(25,3,40,.18)}.thumb{width:116px;height:78px;display:grid;place-items:center;flex-shrink:0;overflow:hidden;border-radius:8px;background:linear-gradient(135deg,#35104b,#c52fda);color:#fff;font-size:12px}.thumb img{width:100%;height:100%;object-fit:cover}.info{flex:1}.info h2{margin:0 0 6px;color:#fff;font-size:17px}.info p{margin:0 0 8px;color:rgba(255,255,255,.7);font-size:12px}.reason{color:#ffb1c1!important}@media(max-width:600px){.heading{align-items:start;gap:18px;flex-direction:column}.list article{align-items:flex-start;flex-wrap:wrap}.list article .el-button{margin-left:134px}}
</style>
