<script setup lang="ts">
import { onMounted, reactive, ref, watch } from 'vue'
import { ElMessage } from 'element-plus'
import { useRoute } from 'vue-router'
import { createNotice, getAdminNotices, updateNotice, updateNoticeStatus, type Notice } from '@/api/community'
import AdminSearchPanel from '@/components/AdminSearchPanel.vue'
const route=useRoute();const records=ref<Notice[]>([]);const loading=ref(true);const dialog=ref(false);const saving=ref(false);const editing=ref<Notice>();const form=reactive({title:'',content:'',topFlag:false});const labels:Record<string,string>={DRAFT:'草稿',PUBLISHED:'已发布',OFFLINE:'已下线'}
async function load(){loading.value=true;try{const result=await getAdminNotices({page:1,pageSize:100,status:String(route.query.status||'')});const keyword=String(route.query.keyword||'').toLowerCase();records.value=result.data.records.filter(notice=>!keyword||notice.title.toLowerCase().includes(keyword))}finally{loading.value=false}}onMounted(load);watch(()=>route.fullPath,load)
function openCreate(){editing.value=undefined;Object.assign(form,{title:'',content:'',topFlag:false});dialog.value=true}function openEdit(notice:Notice){editing.value=notice;Object.assign(form,{title:notice.title,content:notice.content,topFlag:notice.topFlag});dialog.value=true}
async function save(){if(!form.title.trim()||!form.content.trim()){ElMessage.error('请填写公告标题和内容');return}saving.value=true;try{editing.value?await updateNotice(editing.value.id,form):await createNotice(form);dialog.value=false;ElMessage.success('公告已保存');await load()}finally{saving.value=false}}
async function status(notice:Notice,value:string){await updateNoticeStatus(notice.id,value);ElMessage.success('公告状态已更新');await load()}
</script>
<template><section class="content"><div class="title"><div><h1>公告管理</h1><p>发布社团通知，并控制公告置顶与展示状态。</p></div><div><el-button @click="load">刷新</el-button><el-button type="primary" @click="openCreate">新增公告</el-button></div></div><AdminSearchPanel /><el-table v-loading="loading" :data="records"><el-table-column prop="title" label="公告标题" min-width="260"/><el-table-column label="置顶" width="90"><template #default="scope"><el-tag v-if="scope.row.topFlag" type="danger">置顶</el-tag><span v-else>-</span></template></el-table-column><el-table-column label="发布时间" min-width="170"><template #default="scope">{{scope.row.publishTime?.replace('T',' ').slice(0,16)||'-'}}</template></el-table-column><el-table-column label="状态"><template #default="scope"><el-tag>{{labels[scope.row.publishStatus]}}</el-tag></template></el-table-column><el-table-column label="操作" width="250"><template #default="scope"><el-button link @click="openEdit(scope.row)">编辑</el-button><el-button v-if="scope.row.publishStatus!=='PUBLISHED'" link type="success" @click="status(scope.row,'PUBLISHED')">发布</el-button><el-button v-if="scope.row.publishStatus==='PUBLISHED'" link type="warning" @click="status(scope.row,'OFFLINE')">下线</el-button></template></el-table-column></el-table><el-empty v-if="!loading&&!records.length" description="暂无公告"/><el-dialog v-model="dialog" :title="editing?'编辑公告':'新增公告'" width="580px"><el-form label-position="top"><el-form-item label="公告标题" required><el-input v-model="form.title" maxlength="120"/></el-form-item><el-form-item label="公告内容" required><el-input v-model="form.content" type="textarea" :rows="8" maxlength="10000"/></el-form-item><el-form-item><el-checkbox v-model="form.topFlag">置顶展示</el-checkbox></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog></section></template>
<style scoped>.content{padding:0}.title{display:flex;justify-content:space-between;align-items:start;margin-bottom:20px}.title h1{margin:0;color:var(--df-primary-950)}.title p{margin:8px 0 0;color:#77717e}</style>
