<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import { getOverview, type Overview } from '@/api/profile'
const router=useRouter();const auth=useAuthStore();const overview=ref<Overview>();const loading=ref(true)
onMounted(async()=>{try{overview.value=(await getOverview()).data}finally{loading.value=false}})
const cards=[['作品','workCount','/profile/works'],['活动','activityCount','/profile/activities'],['完成课时','completedLessonCount','/profile/courses'],['我的收藏','collectionCount','/profile/collections']] as const
</script>
<template><main class="profile-page" v-loading="loading"><section v-if="overview" class="profile-content"><div class="profile-head"><div class="avatar">{{(auth.user?.nickname||'舞').slice(0,1)}}</div><div><p class="eyebrow">MY GROWTH</p><h1>{{auth.user?.nickname}}的成长档案</h1><p>{{overview.levelName}} · {{overview.totalPoints}} 积分</p></div><el-button @click="router.push('/profile/points')">积分明细</el-button></div><section class="level"><div><span>成长进度</span><b>{{overview.levelName}}</b></div><el-progress :percentage="overview.levelProgress" :stroke-width="9" /></section><section class="stats"><button v-for="card in cards" :key="card[0]" type="button" @click="router.push(card[2])"><b>{{overview[card[1]]}}</b><span>{{card[0]}}</span></button><div><b>{{overview.receivedLikeCount}}</b><span>获得点赞</span></div></section></section></main></template>
<style scoped>.profile-page{min-height:100vh;padding:58px 24px;color:#fff}.profile-content{max-width:1040px;margin:auto}.profile-head{display:flex;align-items:center;gap:18px}.avatar{display:grid;place-items:center;width:74px;height:74px;border-radius:50%;background:linear-gradient(135deg,#b92bd1,#ef9afa);font-size:30px}.profile-head h1{margin:5px 0;font-size:36px}.profile-head p{margin:0;color:rgba(255,255,255,.7)}.profile-head .el-button{margin-left:auto}.eyebrow{color:#f0a8fb!important;font-size:12px;letter-spacing:2px}.level{margin:38px 0 22px;padding:22px;border:1px solid rgba(244,205,250,.24);border-radius:10px;background:rgba(54,12,70,.8)}.level div{display:flex;justify-content:space-between;margin-bottom:16px}.level span{color:rgba(255,255,255,.68)}.level b{color:#f0a8fb}.stats{display:grid;grid-template-columns:repeat(5,1fr);gap:14px}.stats button,.stats>div{display:grid;gap:8px;padding:20px;border:1px solid rgba(244,205,250,.24);border-radius:10px;background:rgba(54,12,70,.8);color:#fff;text-align:left}.stats button{cursor:pointer}.stats b{font-size:28px}.stats span{color:rgba(255,255,255,.65);font-size:13px}@media(max-width:760px){.stats{grid-template-columns:repeat(2,1fr)}.profile-head{align-items:start;flex-wrap:wrap}.profile-head .el-button{margin-left:92px}}</style>
