<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { getWorks, type Work } from '@/api/works'
const router = useRouter(); const records = ref<Work[]>([]); const loading = ref(true); const danceType = ref(''); const sortBy = ref('latest')
async function load() { loading.value = true; try { records.value = (await getWorks({ page: 1, pageSize: 24, danceType: danceType.value || undefined, sortBy: sortBy.value })).data.records } finally { loading.value = false } }
onMounted(load)
</script>
<template><main class="works-page"><section class="works-heading"><div><p class="eyebrow">DANCE WORKS</p><h1>作品社区</h1><p>看见每一次练习，也分享你的舞台。</p></div><div class="heading-actions"><el-button type="primary" @click="router.push('/works/create')">发布作品</el-button><el-button plain @click="router.push('/profile/works')">我的作品</el-button></div></section><section class="toolbar"><el-select v-model="danceType" clearable placeholder="全部舞种" @change="load"><el-option label="Hip-hop" value="Hip-hop" /><el-option label="Jazz Funk" value="Jazz Funk" /><el-option label="Breaking" value="Breaking" /></el-select><el-segmented v-model="sortBy" :options="[{ label: '最新发布', value: 'latest' }, { label: '热门作品', value: 'popular' }]" @change="load" /></section><section v-loading="loading" class="work-grid"><el-empty v-if="!loading && !records.length" description="暂时还没有公开作品" /><article v-for="work in records" :key="work.id" class="work-card" @click="router.push(`/works/${work.id}`)"><div class="media-preview"><img v-if="work.mediaType === 'IMAGE'" :src="work.mediaUrl" :alt="work.title" /><video v-else :src="work.mediaUrl" muted preload="metadata" /></div><div class="work-body"><span class="work-type">{{ work.danceType }}</span><h2>{{ work.title }}</h2><p>{{ work.authorName }} · {{ work.viewCount }} 次浏览</p><div class="counts"><span>♡ {{ work.likeCount }}</span><span>☆ {{ work.collectionCount }}</span><span>评论 {{ work.commentCount }}</span></div></div></article></section></main></template>
<style scoped>.works-page{min-height:100vh;background:transparent;color:#fff}.works-heading{display:flex;align-items:end;justify-content:space-between;max-width:1120px;margin:auto;padding:64px 24px 30px}.eyebrow{margin:0 0 10px;color:#f0a8fb;font-size:12px;letter-spacing:2px;font-weight:700}.works-heading h1{margin:0 0 10px;font-size:46px}.works-heading p:last-child{margin:0;color:rgba(255,255,255,.7)}.heading-actions{display:flex;gap:10px}.toolbar{display:flex;gap:12px;max-width:1120px;margin:auto;padding:0 24px 30px}.work-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:18px;max-width:1120px;min-height:300px;margin:auto;padding:0 24px 60px}.work-card{overflow:hidden;border:1px solid rgba(244,205,250,.24);border-radius:14px;background:rgba(54,12,70,.8);box-shadow:0 14px 32px rgba(25,3,40,.2);cursor:pointer;transition:transform .2s,border-color .2s}.work-card:hover{transform:translateY(-4px);border-color:rgba(240,168,251,.6)}.media-preview{height:190px;background:linear-gradient(135deg,#35104b,#bd2ed1)}.media-preview img,.media-preview video{width:100%;height:100%;object-fit:cover}.work-body{padding:14px}.work-type{color:#f0a8fb;font-size:11px}.work-body h2{margin:8px 0;color:#fff;font-size:17px}.work-body p{margin:0;color:rgba(255,255,255,.62);font-size:12px}.counts{display:flex;gap:12px;margin-top:14px;color:rgba(255,255,255,.78);font-size:12px}@media(max-width:800px){.work-grid{grid-template-columns:repeat(2,1fr)}.works-heading{align-items:start;gap:20px;flex-direction:column}}@media(max-width:520px){.work-grid{grid-template-columns:1fr}.toolbar{flex-wrap:wrap}}
</style>
