<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useRoute } from 'vue-router'
import { auditWork, getAdminWorks, type Work } from '@/api/works'
const records=ref<Work[]>([]); const loading=ref(true); const route=useRoute(); const labels:Record<string,string>={PENDING:'待审核',PUBLISHED:'已发布',REJECTED:'已驳回',OFFLINE:'已下架'}
async function load(){loading.value=true;try{const all=(await getAdminWorks({page:1,pageSize:100,status:String(route.query.status||'')})).data.records;const keyword=String(route.query.keyword||'').toLowerCase();records.value=all.filter(item=>(!keyword||`${item.title} ${item.authorName}`.toLowerCase().includes(keyword))&&(!route.query.danceType||item.danceType===route.query.danceType))}finally{loading.value=false}} onMounted(load); watch(() => route.fullPath, load)
async function audit(row:Work,next:string){let reason='';if(next==='REJECTED'){try{reason=(await ElMessageBox.prompt('请输入驳回原因','驳回作品',{inputPattern:/\S+/,inputErrorMessage:'请输入原因'})).value}catch{return}}await auditWork(row.id,next,reason);ElMessage.success('作品审核状态已更新');await load()}
</script>
<template><section class="content"><div class="title"><div><h1>作品审核</h1><p>审核用户提交的作品，只有通过后才会公开展示。</p></div><el-button @click="load">刷新</el-button></div><el-table v-loading="loading" :data="records"><el-table-column prop="title" label="作品名称" min-width="220"/><el-table-column prop="authorName" label="作者"/><el-table-column prop="danceType" label="舞种"/><el-table-column label="状态"><template #default="scope"><el-tag>{{labels[scope.row.auditStatus]}}</el-tag></template></el-table-column><el-table-column label="操作" width="230"><template #default="scope"><el-button link @click="$router.push(`/admin/works/${scope.row.id}`)">预览</el-button><el-button v-if="scope.row.auditStatus==='PENDING'" link type="success" @click="audit(scope.row,'PUBLISHED')">通过</el-button><el-button v-if="scope.row.auditStatus==='PENDING'" link type="danger" @click="audit(scope.row,'REJECTED')">驳回</el-button><el-button v-if="scope.row.auditStatus==='PUBLISHED'" link type="warning" @click="audit(scope.row,'OFFLINE')">下架</el-button></template></el-table-column></el-table><el-empty v-if="!loading&&!records.length" description="暂无作品"/></section></template>
<style scoped>.content{padding:0}.title{display:flex;align-items:start;justify-content:space-between;margin-bottom:20px}.title h1{margin:0;color:var(--df-primary-950)}.title p{margin:8px 0 0;color:#77717e}</style>
