<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { addComment, getComments, getWork, toggleCollection, toggleLike, type Work, type WorkComment } from '@/api/works'
const route=useRoute();const router=useRouter();const work=ref<Work|null>(null);const comments=ref<WorkComment[]>([]);const loading=ref(true);const comment=reactive({content:''})
onMounted(async()=>{try{work.value=(await getWork(String(route.params.id))).data;comments.value=(await getComments(String(route.params.id))).data}finally{loading.value=false}})
async function like(){if(work.value)Object.assign(work.value,await toggleLike(String(work.value.id)).then(r=>r.data))}
async function collect(){if(work.value)Object.assign(work.value,await toggleCollection(String(work.value.id)).then(r=>r.data))}
async function submit(){if(!comment.content.trim())return;await addComment(String(route.params.id),comment);comment.content='';comments.value=(await getComments(String(route.params.id))).data}
</script>
<template><main class="detail-page"><section v-loading="loading" class="detail" v-if="work"><el-link @click="router.push('/works')">返回作品社区</el-link><p class="eyebrow">{{ work.danceType }} · {{ work.authorName }}</p><h1>{{ work.title }}</h1><p class="description">{{ work.description || '记录舞者的每一次表达。' }}</p><div class="media"><img v-if="work.mediaType==='IMAGE'" :src="work.mediaUrl" :alt="work.title" /><video v-else controls :src="work.mediaUrl" /></div><div class="actions"><el-button :type="work.liked?'primary':'default'" @click="like">{{ work.liked?'已点赞':'点赞' }} {{ work.likeCount }}</el-button><el-button :type="work.collected?'primary':'default'" @click="collect">{{ work.collected?'已收藏':'收藏' }} {{ work.collectionCount }}</el-button><span>浏览 {{ work.viewCount }}</span></div><section class="comments"><h2>评论 <small>{{ work.commentCount }}</small></h2><div class="comment-form"><el-input v-model="comment.content" placeholder="说点什么" maxlength="500" @keyup.enter="submit" /><el-button type="primary" @click="submit">发表评论</el-button></div><article v-for="item in comments" :key="item.id"><b>{{ item.authorName }}</b><p>{{ item.content }}</p><time>{{ item.createdAt?.replace('T',' ').slice(0,16) }}</time></article><el-empty v-if="!comments.length" description="还没有评论" /></section></section><section v-else-if="!loading" class="not-found"><el-empty description="作品不存在或尚未通过审核"/><el-button type="primary" @click="router.push('/works')">返回作品社区</el-button></section></main></template>
<style scoped>.detail-page{min-height:100vh;background:transparent;color:#fff}.detail{max-width:880px;margin:auto;padding:34px 36px 42px;border:1px solid rgba(244,205,250,.22);border-radius:16px;background:rgba(54,12,70,.78);box-shadow:0 18px 42px rgba(25,3,40,.22);backdrop-filter:blur(14px)}.not-found{display:grid;place-items:center;min-height:70vh;color:#fff}.eyebrow{margin:24px 0 10px;color:#f0a8fb;font-size:12px;letter-spacing:2px}.detail h1{margin:0 0 10px;color:#fff;font-size:44px}.description{color:rgba(255,255,255,.8);line-height:1.8}.media{display:grid;place-items:center;min-height:360px;margin:28px 0;overflow:hidden;border-radius:14px;background:#230b31}.media img,.media video{max-width:100%;max-height:620px}.actions{display:flex;align-items:center;gap:10px;padding-bottom:26px;border-bottom:1px solid rgba(244,205,250,.2);color:rgba(255,255,255,.7)}.actions span{margin-left:auto}.comments{padding-top:24px}.comments h2{color:#fff}.comments small{color:rgba(255,255,255,.55);font-size:13px}.comment-form{display:flex;gap:10px;margin:18px 0 24px}.comments article{padding:14px 0;border-bottom:1px solid rgba(244,205,250,.16)}.comments article b{color:#f0a8fb}.comments article p{margin:8px 0;color:rgba(255,255,255,.86)}.comments time{color:rgba(255,255,255,.48);font-size:12px}@media(max-width:600px){.detail{padding:26px 20px}.detail h1{font-size:34px}.comment-form{align-items:stretch;flex-direction:column}}
</style>
