<script setup lang="ts">
import { reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { createWork, uploadFile } from '@/api/works'
import { useRouter } from 'vue-router'
const router = useRouter(); const saving = ref(false); const uploading = ref(false); const media = ref<{ url:string; type:string } | null>(null); const form = reactive({ title:'', coverUrl:'', mediaUrl:'', mediaType:'', description:'', danceType:'Hip-hop' })
async function selectFile(file: { raw?: File }) { if (!file.raw) return; uploading.value = true; try { const result = await uploadFile(file.raw); media.value = { url: result.data.url, type: result.data.contentType.startsWith('video/') ? 'VIDEO' : 'IMAGE' }; form.mediaUrl = result.data.url; form.mediaType = media.value.type; ElMessage.success('文件上传成功') } catch { ElMessage.error('文件上传失败，请重试') } finally { uploading.value = false } }
async function submit() { if (!form.title.trim() || !form.mediaUrl || !form.danceType) { ElMessage.error('请完善作品标题、媒体文件和舞种'); return }; saving.value = true; try { await createWork(form); ElMessage.success('作品已提交，等待管理员审核'); router.push('/profile/works') } finally { saving.value = false } }
</script>
<template><main class="create-page"><section class="form-panel"><p class="eyebrow">SHARE YOUR MOVEMENT</p><h1>发布作品</h1><p class="subtitle">上传你的舞蹈影像，审核通过后会展示在作品社区。</p><el-form label-position="top"><el-form-item label="作品标题" required><el-input v-model="form.title" maxlength="100" /></el-form-item><div class="two-col"><el-form-item label="舞种" required><el-select v-model="form.danceType" style="width:100%"><el-option label="Hip-hop" value="Hip-hop" /><el-option label="Jazz Funk" value="Jazz Funk" /><el-option label="Breaking" value="Breaking" /></el-select></el-form-item><el-form-item label="封面地址"><el-input v-model="form.coverUrl" placeholder="可选" /></el-form-item></div><el-form-item label="作品文件" required><el-upload :auto-upload="false" :show-file-list="false" accept="image/*,video/mp4,video/webm,video/quicktime" :on-change="selectFile"><el-button :loading="uploading">选择图片或视频</el-button></el-upload><p class="upload-state">{{ media ? `已选择：${media.type === 'VIDEO' ? '视频' : '图片'}` : '支持图片和视频，最大 100MB' }}</p></el-form-item><el-form-item label="作品描述"><el-input v-model="form.description" type="textarea" :rows="5" maxlength="2000" show-word-limit /></el-form-item><div class="actions"><el-button @click="router.back()">取消</el-button><el-button type="primary" :loading="saving" @click="submit">提交审核</el-button></div></el-form></section></main></template>
<style scoped>.create-page{min-height:100vh;background:transparent;padding:58px 24px}.form-panel{max-width:720px;margin:auto;padding:34px 38px;border:1px solid rgba(244,205,250,.25);border-radius:16px;background:rgba(54,12,70,.86);box-shadow:0 20px 44px rgba(25,3,40,.25)}.eyebrow{margin:0 0 10px;color:#f0a8fb;font-size:12px;letter-spacing:2px;font-weight:700}.form-panel h1{margin:0 0 8px;color:#fff;font-size:38px}.subtitle,.upload-state{color:rgba(255,255,255,.68)}.two-col{display:grid;grid-template-columns:1fr 1fr;gap:16px}.form-panel :deep(.el-form-item__label){color:rgba(255,255,255,.8)}.form-panel :deep(.el-input__wrapper),.form-panel :deep(.el-textarea__inner),.form-panel :deep(.el-select__wrapper){background:rgba(255,255,255,.94)}.actions{display:flex;justify-content:flex-end;gap:10px;margin-top:22px}@media(max-width:600px){.form-panel{padding:26px 20px}.two-col{grid-template-columns:1fr}}
</style>
